// Mirror of packages/render-cut/src/captions.mjs CAPTION_ANIMATION_RECIPES.
// The sandboxed webview cannot import render-cut; test/caption-text-animation.test.mjs guards drift.
export const PREVIEW_CAPTION_ANIMATION_RECIPES: Record<string, string> = {
    "fade-in-out": "from { opacity: 0; } to { opacity: 1; }",
    "soft-fade": "from { opacity: 0; transform: scale(calc(1 + 0.04 * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: scale(1); }",
    "fade-up": "from { opacity: 0; transform: translateY(calc(0.6em * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: translateY(0); }",
    "fade-down": "from { opacity: 0; transform: translateY(calc(-0.6em * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: translateY(0); }",
    "cinematic-fade": "from { opacity: 0; transform: scale(calc(1 - 0.06 * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: scale(1); }",
    "slide-left": "from { opacity: 0; transform: translateX(calc(1.2em * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: translateX(0); }",
    "slide-right": "from { opacity: 0; transform: translateX(calc(-1.2em * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: translateX(0); }",
    "slide-up": "from { opacity: 0; transform: translateY(calc(1.2em * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: translateY(0); }",
    "slide-down": "from { opacity: 0; transform: translateY(calc(-1.2em * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: translateY(0); }",
    "push-left": "from { transform: translateX(calc(2em * var(--akari-anim-amp, 1))); clip-path: inset(0 0 0 100%); } to { transform: translateX(0); clip-path: inset(0); }",
    "push-right": "from { transform: translateX(calc(-2em * var(--akari-anim-amp, 1))); clip-path: inset(0 100% 0 0); } to { transform: translateX(0); clip-path: inset(0); }",
    "push-up": "from { transform: translateY(calc(1.4em * var(--akari-anim-amp, 1))); clip-path: inset(100% 0 0 0); } to { transform: translateY(0); clip-path: inset(0); }",
    "push-down": "from { transform: translateY(calc(-1.4em * var(--akari-anim-amp, 1))); clip-path: inset(0 0 100% 0); } to { transform: translateY(0); clip-path: inset(0); }",
    "rise-soft": "from { opacity: 0; transform: translateY(calc(0.35em * var(--akari-anim-amp, 1))) scale(0.98); } to { opacity: 1; transform: translateY(0) scale(1); }",
    "drop-in": "0% { opacity: 0; transform: translateY(calc(-1.6em * var(--akari-anim-amp, 1))); } 70% { opacity: 1; transform: translateY(calc(0.12em * var(--akari-anim-amp, 1))); } 100% { opacity: 1; transform: translateY(0); }",
    "zoom-in-out": "from { opacity: 0; transform: scale(calc(1 - 0.4 * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: scale(1); }",
    "zoom-pop": "0% { opacity: 0; transform: scale(0.4); } 70% { opacity: 1; transform: scale(calc(1 + 0.12 * var(--akari-anim-amp, 1))); } 100% { opacity: 1; transform: scale(1); }",
    "zoom-pulse": "0% { opacity: 0; transform: scale(0.7); } 55% { opacity: 1; transform: scale(calc(1 + 0.06 * var(--akari-anim-amp, 1))); } 100% { opacity: 1; transform: scale(1); }",
    "pop": "0% { opacity: 0; transform: scale(0.5); } 65% { opacity: 1; transform: scale(calc(1 + 0.18 * var(--akari-anim-amp, 1))); } 100% { opacity: 1; transform: scale(1); }",
    "bounce": "0% { opacity: 0; transform: translateY(calc(-1.2em * var(--akari-anim-amp, 1))); } 55% { opacity: 1; transform: translateY(calc(0.22em * var(--akari-anim-amp, 1))); } 75% { transform: translateY(calc(-0.1em * var(--akari-anim-amp, 1))); } 100% { opacity: 1; transform: translateY(0); }",
    "squash-pop": "0% { opacity: 0; transform: scale(1.4, 0.4); } 60% { opacity: 1; transform: scale(0.92, 1.1); } 100% { opacity: 1; transform: scale(1); }",
    "stretch-in": "0% { opacity: 0; transform: scaleX(0.2); } 70% { opacity: 1; transform: scaleX(calc(1 + 0.08 * var(--akari-anim-amp, 1))); } 100% { opacity: 1; transform: scaleX(1); }",
    "stomp": "0% { opacity: 0; transform: scale(calc(1 + 0.9 * var(--akari-anim-amp, 1))); } 60% { opacity: 1; transform: scale(0.96); } 100% { opacity: 1; transform: scale(1); }",
    "snap": "0% { opacity: 0; transform: rotate(calc(-6deg * var(--akari-anim-amp, 1))) scale(0.8); } 70% { opacity: 1; transform: rotate(calc(2deg * var(--akari-anim-amp, 1))) scale(1.04); } 100% { opacity: 1; transform: rotate(0) scale(1); }",
    "rotate-in": "from { opacity: 0; transform: rotate(calc(-12deg * var(--akari-anim-amp, 1))) scale(0.9); } to { opacity: 1; transform: rotate(0) scale(1); }",
    "spin-in": "from { opacity: 0; transform: rotate(calc(-180deg * var(--akari-anim-amp, 1))) scale(0.5); } to { opacity: 1; transform: rotate(0) scale(1); }",
    "roll-in": "from { opacity: 0; transform: translateX(calc(-2em * var(--akari-anim-amp, 1))) rotate(calc(-120deg * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: translateX(0) rotate(0); }",
    "spiral-in": "from { opacity: 0; transform: rotate(calc(240deg * var(--akari-anim-amp, 1))) scale(0.2); } to { opacity: 1; transform: rotate(0) scale(1); }",
    "swing": "0% { opacity: 0; transform: rotate(calc(14deg * var(--akari-anim-amp, 1))); transform-origin: top center; } 60% { opacity: 1; transform: rotate(calc(-6deg * var(--akari-anim-amp, 1))); transform-origin: top center; } 100% { opacity: 1; transform: rotate(0); transform-origin: top center; }",
    "shake": "0%, 100% { transform: translateX(0); } 20% { transform: translateX(calc(-0.16em * var(--akari-anim-amp, 1))); } 40% { transform: translateX(calc(0.14em * var(--akari-anim-amp, 1))); } 60% { transform: translateX(calc(-0.1em * var(--akari-anim-amp, 1))); } 80% { transform: translateX(calc(0.06em * var(--akari-anim-amp, 1))); }",
    "jitter": "0%, 100% { transform: translate(0, 0); } 25% { transform: translate(calc(0.05em * var(--akari-anim-amp, 1)), calc(-0.04em * var(--akari-anim-amp, 1))); } 50% { transform: translate(calc(-0.05em * var(--akari-anim-amp, 1)), calc(0.04em * var(--akari-anim-amp, 1))); } 75% { transform: translate(calc(0.03em * var(--akari-anim-amp, 1)), calc(0.05em * var(--akari-anim-amp, 1))); }",
    "glitch": "0% { opacity: 0; transform: translate(calc(-0.2em * var(--akari-anim-amp, 1)), 0); clip-path: inset(0 0 60% 0); } 30% { opacity: 1; transform: translate(calc(0.12em * var(--akari-anim-amp, 1)), 0); clip-path: inset(30% 0 20% 0); } 60% { transform: translate(calc(-0.06em * var(--akari-anim-amp, 1)), 0); clip-path: inset(10% 0 45% 0); } 100% { opacity: 1; transform: translate(0, 0); clip-path: inset(0); }",
    "flash": "0% { opacity: 0; } 30% { opacity: 1; } 45% { opacity: 0.2; } 60% { opacity: 1; } 75% { opacity: 0.5; } 100% { opacity: 1; }",
    "heartbeat": "0% { transform: scale(1); } 25% { transform: scale(calc(1 + 0.12 * var(--akari-anim-amp, 1))); } 45% { transform: scale(1); } 65% { transform: scale(calc(1 + 0.08 * var(--akari-anim-amp, 1))); } 100% { transform: scale(1); }",
    "typewriter": "from { clip-path: inset(0 100% 0 0); } to { clip-path: inset(0 0 0 0); }",
    "wipe-left": "from { clip-path: inset(0 0 0 100%); } to { clip-path: inset(0); }",
    "wipe-right": "from { clip-path: inset(0 100% 0 0); } to { clip-path: inset(0); }",
    "wobble": "0%, 100% { transform: rotate(calc(-1.6deg * var(--akari-anim-amp, 1))); } 50% { transform: rotate(calc(1.6deg * var(--akari-anim-amp, 1))); }",
    "float": "0%, 100% { transform: translateY(0); } 50% { transform: translateY(calc(-0.22em * var(--akari-anim-amp, 1))); }",
    "breath": "0%, 100% { transform: scale(1); opacity: 1; } 50% { transform: scale(calc(1 + 0.03 * var(--akari-anim-amp, 1))); opacity: 0.92; }",
    "neon-flicker": "0%, 100% { opacity: 1; } 8% { opacity: 0.6; } 12% { opacity: 1; } 40% { opacity: 0.85; } 44% { opacity: 1; } 70% { opacity: 0.4; } 74% { opacity: 1; }",
    "hologram": "0%, 100% { opacity: 1; transform: translateX(0); } 30% { opacity: 0.75; transform: translateX(calc(0.03em * var(--akari-anim-amp, 1))); } 60% { opacity: 0.9; transform: translateX(calc(-0.03em * var(--akari-anim-amp, 1))); }",
    "retro-flicker": "0%, 100% { opacity: 1; } 25% { opacity: 0.7; } 50% { opacity: 1; } 75% { opacity: 0.8; }",
    "caption-rise": "from { opacity: 0; transform: translateY(calc(0.5em * var(--akari-anim-amp, 1))); } to { opacity: 1; transform: translateY(0); }",
    "news-ticker": "from { transform: translateX(100%); } to { transform: translateX(-100%); }",
    "marquee-left": "from { transform: translateX(100%); } to { transform: translateX(-100%); }",
    "crawl-up": "from { transform: translateY(100%); } to { transform: translateY(-100%); }"
};
