import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../src/browser/akari-preview-open-handler.ts',import.meta.url),'utf8');
function block(name){const at=source.indexOf(`            const ${name} =`),end=source.indexOf('\n            };',at);assert.ok(at>=0);return source.slice(at,end+15);}
function fixture(write){let model={x:0,y:0,scale:1,rotate:0},serial=0;const ended=[],window=new EventTarget();window.akari={beginPreviewGesture:()=>++serial,endPreviewGesture:id=>ended.push(id),interaction:{hideSnapGuides(){}}};const target=new EventTarget();Object.assign(target,{setPointerCapture(){},hasPointerCapture:()=>false,releasePointerCapture(){}});const run=new Function('window','console',`const CLICK_THRESHOLD_PX=3,isPlaying=false;let cancelActiveTransform=null,latestTransformGesture=0;${block('runTransformGesture')}return runTransformGesture`)(window,{warn(){}});const start=()=>run({pointerId:1,clientX:0,clientY:0,currentTarget:target,preventDefault(){},stopPropagation(){}},(e,o)=>({...o,x:o.x+e.clientX}),()=>model,v=>model=v,()=>{},write);const emit=(type,x)=>{const e=new Event(type);Object.assign(e,{pointerId:1,clientX:x,clientY:0});window.dispatchEvent(e)};return {start,emit,model:()=>model,ended};}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('release position is committed once even without any pointermove',async()=>{const writes=[];const f=fixture(async v=>writes.push(v));f.start();f.emit('pointerup',50);f.emit('pointerup',70);await settle();assert.equal(writes.length,1);assert.equal(writes[0].x,50);assert.deepEqual(f.ended,[1]);});
test('pointer cancellation restores the original position without writing',async()=>{const writes=[];const f=fixture(async v=>writes.push(v));f.start();f.emit('pointermove',50);f.emit('pointercancel',60);await settle();assert.equal(f.model().x,0);assert.equal(writes.length,0);});
test('an older failed write cannot roll back a newer gesture',async()=>{let rejectFirst;let calls=0;const f=fixture(()=>++calls===1?new Promise((_,reject)=>rejectFirst=reject):Promise.resolve());f.start();f.emit('pointerup',50);f.start();f.emit('pointerup',20);rejectFirst(Error('old write failed'));await settle();assert.equal(f.model().x,70);assert.equal(f.ended.length,2);});
test('inspector layout scale changes do not inject a movement delta',()=>{let scale=1;const window={akari:{interaction:{currentDisplayScale:()=>scale,hideSnapGuides(){}}}};const make=new Function('window',`${block('movementHandler')}return movementHandler`)(window);const move=make({clientX:0,clientY:0},()=>{}),original={x:0,y:0,scale:1};assert.equal(move({clientX:50,clientY:0,shiftKey:true},original).x,50);scale=.5;assert.equal(move({clientX:50,clientY:0,shiftKey:true},original).x,50);assert.equal(move({clientX:60,clientY:0,shiftKey:true},original).x,70);});
