import { clearLog, clickOutput, dragOutput, hostCdp, installProbe, seek, sleep, snapshot, viewCdp } from './pss.mjs';
const [project] = process.argv.slice(2);
const host = await hostCdp(); const view = await viewCdp(); await installProbe(view);
const snap = async n => { const s = await snapshot(host, view, n); console.log(n, JSON.stringify({ t: await view.eval(`Number(document.getElementById('seek').value)`), layer: s.closure?.selectedLayerId, cut: s.closure?.cutSelected, ov: s.closure?.requestedOverlayId, tl: s.timeline.selected })); };
await seek(host, project, 1); await sleep(1500);
await dragOutput(host, view, [220, 160], [260, 190]); await sleep(2500); await snap('moved-photo-a@1');
await seek(host, project, 0.5); await sleep(1500); await snap('seek0.5');
await clearLog(view); await clickOutput(host, view, 220, 420); await sleep(1200); await snap('click-base@(220,420)');
await clickOutput(host, view, 260, 190); await sleep(1200); await snap('click-photo-a');
await clickOutput(host, view, 700, 500); await sleep(1200); await snap('click-base@(700,500)');
host.close(); view.cdp.close(); process.exit(0);
