// curated-telop — 代表 25 件（telop）の手動タグ整備。汎用（ロワーサード・字幕・バラエティ感情
// スタンプ・レシピ等、使用頻度が高そうなもの）を優先して選定（task.md の指示どおり）。
// tags は雰囲気/用途の日本語タグ。他の 210 件は port-telop.mjs が id から機械変換したタグを使う。
export const CURATED_TELOP_TAGS = {
  ref3_name_rounded: ["人名スーパー", "朝番組", "角丸", "ニュース", "汎用"],
  ref3_l_bar_lower: ["インタビュー", "Lバー", "報道", "汎用"],
  ref3_navy_lower: ["ビジネス", "ネイビー", "解説", "落ち着き"],
  ref3_thin_separator: ["ミニマル", "細線", "上品", "汎用"],
  ref3_sports_score: ["スポーツ", "速報", "スコア", "実況"],
  ref3_chapter_tag: ["解説動画", "チャプター", "常駐", "目次"],
  ref3_corner_title_line: ["コーナータイトル", "ミニマル", "下線"],
  ref3_typewriter_mono: ["Vlog", "日付スタンプ", "フィルム風", "ノスタルジア"],
  ref3_hormozi_snap: ["Shorts", "TikTok", "ワードスナップ", "強調", "定番"],
  ref3_beast_stamp: ["YouTube", "極太", "スタンプ", "欧米キャプション"],
  ref3_netflix_sub: ["字幕", "配信", "標準"],
  ref3_wcag_minimal: ["字幕", "アクセシビリティ", "ミニマル"],
  ref3_nhk_ud: ["字幕", "UD", "可読性", "公共放送"],
  ref3_zabuton_pill: ["字幕", "座布団", "角丸", "カジュアル"],
  ref3_scandi_bar: ["字幕", "半透明バー", "北欧風", "上品"],
  ref3_cm_popon: ["字幕", "CM", "ポップオン"],
  ref3_keycolor_band: ["字幕", "キーカラー帯", "テレビ番組風"],
  ref3_numbered_badge: ["ハウツー", "リスト", "番号バッジ", "解説"],
  ref3_quantity_highlight: ["レシピ", "料理", "分量強調"],
  ref3_neon_stream: ["ネオン", "発光", "ポップ", "映え"],
  ref3_emotion_rage: ["バラエティ", "感情", "怒り", "ツッコミ"],
  ref3_emotion_sorrow: ["バラエティ", "感情", "悲しみ", "薄青"],
  ref3_beat_stamp: ["キネティックタイポ", "ビート", "強調", "短語"],
  ref3_stick_note: ["付箋", "暮らし系", "メモ風", "カジュアル"],
  ref3_recipe_card: ["レシピ", "カード", "料理", "スライド"],
}
