// BEFORE / AFTER で共通の観測式（ラッパー作成の検証スクリプト）。
import { S } from './common.mjs';
export const BAR = '[data-akari-ui="preview-context-bar"]';
export const MORE = '[data-akari-ui="preview-element-more"]';
export const POP = '[data-akari-ui="preview-context-window"]';
export const PANEL = `(()=>{const e=document.querySelector('[data-akari-caption-panel]');return e?e.getAttribute('data-akari-caption-panel'):null})()`;
// 出力プレビューの字幕（webview の中）の見た目
export const PLATE = id => `(()=>{const p=[...document.querySelectorAll('.caption-row-plate')].find(e=>e.id.startsWith('caption-plate-'+${S(id)}));if(!p)return null;const l=p.querySelector('.akari-caption__line');if(!l)return null;const cs=getComputedStyle(l);const b=p.querySelector('.akari-caption__block')||l;const bs=getComputedStyle(b);return{font:cs.fontFamily.slice(0,80),weight:cs.fontWeight,color:cs.color,stroke:cs.webkitTextStrokeWidth+' '+cs.webkitTextStrokeColor,shadow:cs.textShadow.slice(0,80),bg:bs.backgroundColor}})()`;
// フォント一覧の行
export const FONT_ROWS = `[...document.querySelectorAll('[data-akari-font-row]')].map(r=>{const n=r.querySelector('.akari-caption-font-name');const cs=n?getComputedStyle(n):null;return{id:r.dataset.akariFontRow,text:(r.innerText||'').replace(/\\s+/g,' ').trim().slice(0,60),name:n?.textContent.trim()??null,nameFont:cs?.fontFamily.split(',')[0].replace(/"/g,'').trim()??null,nameSize:cs?.fontSize??null}})`;
// 「…」の中身
export const MORE_ITEMS = `(()=>{const m=document.querySelector(${S(MORE)});const vis=n=>!!n&&n.getClientRects().length>0&&!n.hidden&&getComputedStyle(n).display!=='none';if(!vis(m))return null;const r=m.getBoundingClientRect();return{rect:{w:Math.round(r.width),h:Math.round(r.height)},items:[...m.querySelectorAll('[data-akari-bar-item]')].filter(vis).filter(n=>!n.closest('.akari-ctx-size')||n.matches('.akari-ctx-size')).map(n=>{const b=n.getBoundingClientRect();const label=n.querySelector('.akari-ctx-caption-overflow-name');const icon=n.querySelector('.akari-ctx-caption-overflow-icon');const ir=icon?.getBoundingClientRect();const lr=label?.getBoundingClientRect();return{key:n.getAttribute('data-akari-bar-item'),visibleText:(n.innerText||'').replace(/\\s+/g,' ').trim(),aria:n.getAttribute('aria-label'),pressed:n.getAttribute('aria-pressed'),cls:n.className,w:Math.round(b.width),h:Math.round(b.height),label:label?{text:label.textContent.trim(),clipped:label.scrollWidth>label.clientWidth+1,overflow:getComputedStyle(label).textOverflow}:null,icon:icon?{w:Math.round(ir.width),overflows:icon.scrollWidth>icon.clientWidth+1,text:icon.textContent.trim(),svg:!!icon.querySelector('svg'),overlapsLabel:!!lr&&ir.right>lr.left+0.5}:null}})}})()`;
// 編集パネルの状態（どのタブ・どの欄が見えているか・目立たせている要素）
export const INSPECTOR = `(()=>{const root=document.querySelector('[data-akari-ui="panel:inspector"]');if(!root)return null;const vr=root.getBoundingClientRect();const tab=root.querySelector('.akari-inspector-tab.is-active');const secs=[...root.querySelectorAll('[data-akari-ui^="section:inspector-"]')].map(s=>{const r=s.getBoundingClientRect();const body=s.querySelector('.akari-inspector-section-body');const visTop=Math.max(r.top,vr.top),visBot=Math.min(r.bottom,vr.bottom);return{id:s.getAttribute('data-akari-ui').slice(18),open:body?!body.hasAttribute('hidden'):null,top:Math.round(r.top-vr.top),h:Math.round(r.height),visiblePx:Math.max(0,Math.round(visBot-visTop))}});const flash=[...root.querySelectorAll('.akari-inspector-reveal-flash, .akari-inspector-pulse, [class*="pulse"], [class*="flash"]')].map(e=>(e.getAttribute('data-akari-ui')||e.getAttribute('data-inspector-field')||e.className).slice(0,60));const scrollers=[...root.querySelectorAll('*')].filter(e=>e.scrollHeight>e.clientHeight+20&&/auto|scroll/.test(getComputedStyle(e).overflowY)).map(e=>({cls:String(e.className).slice(0,50),top:Math.round(e.scrollTop)}));return{panel:${PANEL},tab:tab?.getAttribute('data-akari-ui')??null,sections:secs,flash,scrollers,log:window.__cpfFlash||[]}})()`;
// 目立たせたクラスが付いた要素を記録する（650ms で外れるため MutationObserver で拾う）
export const HOOK_FLASH = `(()=>{window.__cpfFlash=[];if(!window.__cpfFlashObs){window.__cpfFlashObs=new MutationObserver(ms=>{for(const m of ms){const e=m.target;if(m.attributeName==='class'&&e.classList&&[...e.classList].some(c=>/flash|pulse|reveal/.test(c)))window.__cpfFlash.push({cls:[...e.classList].filter(c=>/flash|pulse|reveal/.test(c)).join(' '),ui:e.getAttribute('data-akari-ui')||e.getAttribute('data-inspector-field')||e.tagName})}});window.__cpfFlashObs.observe(document.body,{attributes:true,attributeFilter:['class'],subtree:true})}return true})()`;
