import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseEdit} from '../../../../../packages/edit-store/lib/edit-store.js';
import * as visual from '../../../../../packages/edit-store/lib/visual-tracks.js';
const code=readFileSync(new URL('../lib/browser/akari-annotations-widget.js',import.meta.url),'utf8');
function method(name){const rest=code.slice(code.indexOf('    async '+name+'('));return rest.slice(0,rest.indexOf('\n    }')+6)}
const Widget=new Function('visual_tracks_1','window','CustomEvent',`return class {${method('commitVisualTrackMove')} ${method('commitTimelineSnapshot')}}`)(visual,{dispatchEvent(){}},class {});

function fixture(){let disk=JSON.stringify({version:0,source:{path:'red.webm'},cuts:[{in:0,out:1,at:2,track:1},{in:0,out:1,at:0,track:0}],layers:[],timeline:{tracks:[{id:'lower',kind:'video',ref:0},{id:'upper',kind:'video',ref:1}]}});const releases=[],history=[];const w=Object.assign(new Widget(),{location:{editUri:{}},pendingVisualWrites:0,timelineWriteTail:Promise.resolve(),historyActionTail:Promise.resolve(),fileService:{readFile:async()=>({value:disk})},trackHeightFor:()=>72,storage:{setData:async()=>{}},trackHeightStorageKey:()=>'',pushHistory:v=>history.push(v),footer:{},revealOutputPreview(){},async reloadEdit(source){const s=source??disk,p=parseEdit(s);this.displayedEditSource=s;if(source===undefined)this.lastSavedEditSource=s;this.cuts=p.cuts;this.layers=p.layers;this.timelineTracks=p.timeline.tracks},async writeEditSnapshotGuarded(source){await new Promise(resolve=>releases.push(resolve));disk=source}});w.reloadEdit();return {w,releases,history,disk:()=>JSON.parse(disk)};}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('moves publish immediately and rapid subsequent drops save in order without reverting the view',async()=>{const f=fixture();const first=f.w.commitVisualTrackMove({kind:'cut-move',index:0,at:2,targetTimelineId:'lower'});assert.equal(f.w.cuts[0].track,0);assert.equal(f.w.timelineTracks.length,1);const second=f.w.commitVisualTrackMove({kind:'cut-move',index:0,at:2.5,targetTimelineId:'lower'});assert.equal(f.w.cuts[0].at,2.5);assert.equal(f.disk().cuts[0].track,1);await settle();f.releases[0]();await first;await settle();assert.equal(f.w.cuts[0].at,2.5);assert.equal(f.disk().cuts[0].at,2);f.releases[1]();await second;assert.equal(f.disk().cuts[0].at,2.5);assert.equal(f.w.pendingVisualWrites,0);assert.equal(f.history.length,2);});
test('a rejected save restores the last persisted layout',async()=>{const f=fixture();f.w.writeEditSnapshotGuarded=async()=>{throw Error('rejected')};await assert.rejects(f.w.commitVisualTrackMove({kind:'cut-move',index:0,at:2,targetTimelineId:'lower'}));assert.equal(f.w.cuts[0].track,1);assert.equal(f.w.timelineTracks.length,2);assert.equal(f.w.pendingVisualWrites,0);});
