import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../lib/browser/akari-annotations-widget.js',import.meta.url),'utf8');
function method(name){const rest=source.slice(source.indexOf('    '+name+'('));return rest.slice(0,rest.indexOf('\n    }')+6)}
class Element{constructor(surface='strip',blocked=false){this.surface=surface;this.blocked=blocked}closest(){return this.blocked?this:null}}
const Widget=new Function('Element',`return class {${['isSeekSurfaceTarget','updateHoverSeek','onStripClick'].map(method).join('\n')}}`)(Element);
function fixture(){const seeks=[],w=Object.assign(new Widget(),{stripScroll:{contains:e=>e.surface==='strip'},rulerBar:{contains:e=>e.surface==='ruler'},playhead:{contains:e=>e.surface==='handle'},strip:{getBoundingClientRect:()=>({left:100,right:500,width:400})},hoverSeek:{style:{display:'none'},dataset:{}},playheadT:3,timeAtClientX:x=>20+(x-100)/40,percent:t=>(t-20)*10,applySelection(){},selectTimeAtClientX:x=>seeks.push(x)});return {w,seeks}}
test('hovering empty space shows a predicted position without seeking',()=>{const {w,seeks}=fixture();w.updateHoverSeek({target:new Element(),buttons:0,clientX:200});assert.equal(w.hoverSeek.style.display,'block');assert.equal(w.hoverSeek.style.left,'25%');assert.equal(w.hoverSeek.dataset.time,'22.5');assert.equal(w.playheadT,3);assert.deepEqual(seeks,[])});
test('materials, controls, scrollbar gutter, and active gestures hide the guide',()=>{for(const event of [{target:new Element('strip',true),clientX:200},{target:new Element('outside'),clientX:200},{target:new Element('handle'),clientX:200},{target:new Element(),clientX:510},{target:new Element(),clientX:200,buttons:1}]){const {w}=fixture();w.updateHoverSeek({buttons:0,...event});assert.equal(w.hoverSeek.style.display,'none')}const {w}=fixture();w.dragState={};w.updateHoverSeek({target:new Element(),clientX:200,buttons:0});assert.equal(w.hoverSeek.style.display,'none')});
test('ruler and margin clicks seek, while interactive targets and gutter do not',()=>{const {w,seeks}=fixture();w.onStripClick({target:new Element('strip',true),clientX:200});w.onStripClick({target:new Element(),clientX:510});assert.deepEqual(seeks,[]);w.onStripClick({target:new Element('ruler'),clientX:200});w.onStripClick({target:new Element(),clientX:300});assert.deepEqual(seeks,[200,300])});
test('layout refresh rechecks the current hit target and cannot revive a departed pointer',()=>{let callback,calls=0;const target=new Element();const Refresh=new Function('requestAnimationFrame','document',`return class {${method('scheduleSeekHoverRefresh')}}`)(cb=>{callback=cb;return 1},{elementFromPoint:()=>target});const w=Object.assign(new Refresh(),{seekHoverPoint:{x:200,y:20},updateHoverSeek:e=>{calls++;assert.equal(e.target,target);assert.equal(e.clientX,200)}});w.scheduleSeekHoverRefresh();w.scheduleSeekHoverRefresh();callback();assert.equal(calls,1);w.scheduleSeekHoverRefresh();w.seekHoverPoint=undefined;callback();assert.equal(calls,1)});
