import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const repositoryRoot = join(packageRoot, '../..');
const editSchema = JSON.parse(await readFile(join(repositoryRoot, 'packages/schemas/edit.schema.json'), 'utf8'));
const motionSchema = JSON.parse(await readFile(join(repositoryRoot, 'packages/schemas/motion.schema.json'), 'utf8'));
const definitions = editSchema.$defs;

const itemDefinitionNames = [
  'itemV2Media', 'itemV2Html', 'itemV2Shape', 'itemV2Telop', 'itemV2Filter',
  'itemV2Group', 'itemV2Captions', 'itemV2Caption', 'itemV2AudioMedia',
];
const sourceDefinitionNames = [
  'itemSourceMediaV2', 'itemSourceAudioMediaV2', 'itemSourceHtmlV2',
  'itemSourceShapeV2', 'itemSourceTelopV2', 'itemSourceFilterV2', 'itemSourceGroupV2',
  'itemSourceCaptionsV2', 'itemSourceCaptionV2',
];

function propertyKeys(name) {
  return Object.keys(definitions[name]?.properties ?? {});
}

function unique(values) {
  return [...new Set(values)];
}

const itemKeysByDefinition = Object.fromEntries(
  itemDefinitionNames.map(name => [name, propertyKeys(name)]),
);
const sourceKeysByDefinition = Object.fromEntries(
  sourceDefinitionNames.map(name => [name, propertyKeys(name)]),
);
const sourceKinds = sourceDefinitionNames
  .map(name => definitions[name]?.properties?.kind?.const)
  .filter(value => typeof value === 'string');

const values = {
  ITEM_V2_KEYS: unique(Object.values(itemKeysByDefinition).flat()),
  ITEM_SOURCE_V2_KEYS: unique(Object.values(sourceKeysByDefinition).flat()),
  KEYFRAME_V2_KEYS: propertyKeys('keyframeV2'),
  MOTION_V0_KEYS: propertyKeys('motionV0'),
  ANIMATOR_V0_KEYS: propertyKeys('animatorV0'),
  MOTION_FILE_V0_KEYS: Object.keys(motionSchema.properties ?? {}),
  SOURCE_KIND_V2: unique(sourceKinds),
};

const generated = [
  '// Generated by scripts/gen-types.mjs from packages/schemas/edit.schema.json and motion.schema.json.',
  '// Do not edit by hand.',
  '',
  ...Object.entries(values).flatMap(([name, entries]) => [
    `export const ${name} = ${JSON.stringify(entries)} as const;`,
    '',
  ]),
  `export const ITEM_V2_KEYS_BY_DEFINITION = ${JSON.stringify(itemKeysByDefinition, null, 2)} as const;`,
  '',
  `export const ITEM_SOURCE_V2_KEYS_BY_DEFINITION = ${JSON.stringify(sourceKeysByDefinition, null, 2)} as const;`,
  '',
].join('\n');

const destination = join(packageRoot, 'src/generated/edit-v2-keys.ts');
await mkdir(dirname(destination), { recursive: true });
await writeFile(destination, generated, 'utf8');
