import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../src/interaction.js',import.meta.url),'utf8');
function fn(name){const at=source.indexOf(`  function ${name}(`),rest=source.slice(at);assert.ok(at>=0);return rest.slice(0,rest.indexOf('\n  }')+4);}
function fixture(peers=[]){let shown;const api=new Function('window','stage','selectedOverlay','isSelectable','fragmentVideoBounds','outputSize','currentDisplayScale','showSnapGuides',`const SNAP_DISTANCE=8,SNAP_RELEASE_DISTANCE=12;${['closestAxisSnap','snapTargetAxes','alignedAxisGuides','computeSnapCorrection','showAlignedSnapGuides'].map(fn).join('\n')}return {computeSnapCorrection,showAlignedSnapGuides};`)({akari:{snapPeerBounds:()=>peers}},{querySelectorAll:()=>[]},null,()=>true,()=>null,()=>({width:1280,height:720}),()=>1,(x,y)=>shown={x,y});return {api,shown:()=>shown};}
test('centered resize considers moving edges rather than the already-aligned center',()=>{const {api}=fixture();const snap=api.computeSnapCorrection({left:5,right:1275,top:2.8125,bottom:717.1875,centerX:640,centerY:360},null,{resize:true});assert.equal(snap.x.kind,'edge');assert.equal(snap.x.sourceIndex,0);assert.equal(snap.x.target,0);assert.equal(snap.y.kind,'edge');});
test('matching the output frame shows all four edges',()=>{const f=fixture();f.api.showAlignedSnapGuides({left:0,right:1280,top:0,bottom:720,centerX:640,centerY:360},{resize:true});assert.deepEqual(f.shown().x.guides.map(g=>g.target),[0,1280]);assert.deepEqual(f.shown().y.guides.map(g=>g.target),[0,720]);assert.ok([...f.shown().x.guides,...f.shown().y.guides].every(g=>g.kind==='edge'));});
test('other material edges are distinct peer targets while output center remains a center guide',()=>{const {api}=fixture([{left:100,right:300,top:200,bottom:400,centerX:200,centerY:300}]);const snap=api.computeSnapCorrection({left:103,right:203,top:203,bottom:303,centerX:153,centerY:253});assert.equal(snap.x.kind,'peer');assert.equal(snap.y.kind,'peer');const center=api.computeSnapCorrection({left:540,right:740,top:310,bottom:410,centerX:640,centerY:360});assert.equal(center.x.kind,'center');assert.equal(center.y.kind,'center');});
